import torch
import torch.nn as nn
import numpy as np
import os

import mmcv


def patch_normalize(patch_paths, new_path_folder):
    """
    This is used to add more information in patch.pkl
    Used for patch generated by BEVFormer, DETR3D, FCOS3D, PGD, PETR
    NOTE: Only use once 
    """
    for path in patch_paths:
        patch = mmcv.load(path)

        patch = patch + torch.tensor((103.530, 116.280, 123.675)).view(1,3,1,1)
        filename = os.path.split(path)[-1]
        save_info = {
            'patch': patch,
            'totensor': False,
            'img_norm_cfg': dict(
                mean=[103.530, 116.280, 123.675], std=[1.0, 1.0, 1.0], to_rgb=False)
        }
        save_path = os.path.join(new_path_folder, filename)
        mmcv.dump(save_info, save_path)
    
def patch_normalize_bevdet(patch_paths, new_path_folder):
    """
    This is used to add more information in patch.pkl
    Used for patch generated by BEVDet, BEVDepth
    NOTE: Only use once 
    """
    for path in patch_paths:
        patch = mmcv.load(path)

        patch = patch * torch.tensor((0.229, 0.224, 0.225)).view(1,3,1,1) + torch.tensor((0.485, 0.456, 0.406)).view(1,3,1,1)
        patch *= 255.0
        filename = os.path.split(path)[-1]
        save_info = {
            'patch': patch,
            'totensor': True,
            'img_norm_cfg': dict(
                mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], to_rgb=True)
        }
        save_path = os.path.join(new_path_folder, filename)
        mmcv.dump(save_info, save_path)



if __name__=='__main__':

    # # Modify BEVFormer, DETR3D, PETR, FCOS3D, PGD results
    # patch_paths = [
    #     '/home/cixie/shaoyuan/BEV-Attack/mmdet_adv/uni_patch/BEVFormer_coslr_size100_scale0.3_lr10_sample323.pkl',
    #     '/home/cixie/shaoyuan/BEV-Attack/mmdet_adv/uni_patch/Detr3D_coslr_size100_scale0.3_lr10_sample323.pkl',
    #     '/home/cixie/shaoyuan/BEV-Attack/mmdet_adv/uni_patch/FCOSMono3D_coslr_size100_scale0.3_lr10_sample1938.pkl',
    #     '/home/cixie/shaoyuan/BEV-Attack/mmdet_adv/uni_patch/Petr3D_Adv_coslr_size100_scale0.3_lr10_sample323.pkl',
    #     '/home/cixie/shaoyuan/BEV-Attack/mmdet_adv/uni_patch/PGDMono3D_coslr_size100_scale0.3_lr10_sample1938.pkl',
    # ]
    # new_path_folder = '/home/cixie/shaoyuan/BEV-Attack/mmdet_adv/uni_patch_new'
    # patch_normalize(patch_paths, new_path_folder)


    patch_paths = [
        '/home/cixie/shaoyuan/BEV-Attack/zoo/BEVDet/uni_patch/BEVDepth_Adv_coslr_size100_scale0.3_lr0.0392156862745098_sample323.pkl',
        '/home/cixie/shaoyuan/BEV-Attack/zoo/BEVDet/uni_patch/BEVDet_Adv_coslr_size100_scale0.3_lr0.0392156862745098_sample323.pkl',
    ]
    new_path_folder = '/home/cixie/shaoyuan/BEV-Attack/zoo/BEVDet/uni_patch_new'
    patch_normalize_bevdet(patch_paths, new_path_folder)